backend: tensorflow
class_name: Functional
config:
  name: darknet_53
  input_layers:
  - ['input', 0, 0]

  layers:
  - class_name: InputLayer
    config:
      batch_input_shape: !!python/tuple [null, null, null, 3]
      dtype: float32
      name: input
      ragged: false
      sparse: false
    inbound_nodes: []
    name: input

  - class_name: Sequential
    config:
      name: route1
      layers:
      - class_name: yolo>DarkConv
        config:
          filters: 32
          kernel_size: !!python/tuple [3, 3]

      - class_name: yolo>DarkResidual
        config:
          filters: 64
          downsample: True

      - class_name: yolo>DarkResidual
        config:
          filters: 128
          downsample: True

      - class_name: yolo>DarkResidual
        config:
          filters: 128

      - class_name: yolo>DarkResidual
        config:
          filters: 256
          downsample: True
    inbound_nodes:
    - - ['input', 0, 0, {}]
    name: route1

  - class_name: Sequential
    config:
      name: route2
      layers:
      - !repeat:7
        class_name: yolo>DarkResidual
        config:
          filters: 256

      - class_name: yolo>DarkResidual
        config:
          filters: 512
          downsample: True

      - !repeat:7
        class_name: yolo>DarkResidual
        config:
          filters: 512
    inbound_nodes:
    - - ['route1', 0, 0, {}]
    name: route2

  - class_name: Sequential
    config:
      name: route3
      layers:
      - class_name: yolo>DarkResidual
        config:
          filters: 1024
          downsample: True

      - !repeat:3
        class_name: yolo>DarkResidual
        config:
          filters: 1024
    inbound_nodes:
    - - ['route2', 0, 0, {}]
    name: route3

  output_layers:
    route1: ['route1', 0, 0]
    route2: ['route2', 0, 0]
keras_version: 2.4.0
