runtime:
  all_reduce_alg: null
  batchnorm_spatial_persistent: false
  dataset_num_private_threads: null
  default_shard_dim: -1
  distribution_strategy: mirrored
  enable_xla: false
  gpu_thread_mode: null
  loss_scale: null
  mixed_precision_dtype: float32
  num_cores_per_replica: 1
  num_gpus: 1
  num_packs: 1
  per_gpu_thread_count: 0
  run_eagerly: false
  task_index: -1
  tpu: null
  worker_hosts: null
task:
  annotation_file: null
  darknet_load_decoder: false
  gradient_clip_norm: 0.0
  init_checkpoint: ''
  load_darknet_weights: true
  model:
    _boxes: ['[12.0, 16.0]', '[19.0, 36.0]', '[40.0, 28.0]', '[36.0, 75.0]', '[76.0,
        55.0]', '[72.0, 146.0]', '[142.0, 110.0]', '[192.0, 243.0]', '[459.0, 401.0]']
    _input_size: null
    base: v4
    boxes_per_scale: 3
    decoder_activation: leaky
    filter:
      anchor_generation_scale: 416
      class_thresh: 0.45
      ignore_thresh: 0.7
      iou_thresh: 0.45
      loss_type: ciou
      max_boxes: 200
      use_nms: true
      use_tie_breaker: true
    max_level: 5
    min_level: 3
    norm_activation:
      activation: mish
      norm_epsilon: 0.001
      norm_momentum: 0.99
      use_sync_bn: false
    num_classes: 80
  per_category_metrics: false
  train_data:
    block_length: 1
    cache: false
    cycle_length: null
    deterministic: null
    drop_remainder: true
    dtype: float16
    enable_tf_data_service: false
    global_batch_size: 16
    input_path: ''
    is_training: true
    parser:
      fixed_size: true
      image_h: 416
      image_w: 416
      jitter_boxes: 0.005
      jitter_im: 0.1
      max_num_instances: 200
      max_process_size: 608
      min_process_size: 320
      net_down_scale: 32
      pct_rand: 0.5
      random_flip: true
      seed: 10
      shuffle_buffer_size: 10000
    sharding: true
    shuffle_buffer_size: 10000
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_download: true
    tfds_name: coco
    tfds_skip_decoding_feature: ''
    tfds_split: train
  validation_data:
    block_length: 1
    cache: false
    cycle_length: null
    deterministic: null
    drop_remainder: true
    dtype: float16
    enable_tf_data_service: false
    global_batch_size: 8
    input_path: ''
    is_training: false
    parser:
      fixed_size: false
      image_h: 416
      image_w: 416
      jitter_boxes: 0.005
      jitter_im: 0.1
      max_num_instances: 200
      max_process_size: 608
      min_process_size: 320
      net_down_scale: 32
      pct_rand: 0.5
      random_flip: true
      seed: 10
      shuffle_buffer_size: 10000
    sharding: true
    shuffle_buffer_size: 2
    tf_data_service_address: null
    tf_data_service_job_name: null
    tfds_as_supervised: false
    tfds_data_dir: ''
    tfds_download: true
    tfds_name: coco
    tfds_skip_decoding_feature: ''
    tfds_split: validation
  weight_decay: 0.0005
trainer:
  allow_tpu_summary: false
  best_checkpoint_eval_metric: ''
  best_checkpoint_export_subdir: ''
  best_checkpoint_metric_comp: higher
  checkpoint_interval: 1000
  continuous_eval_timeout: 3600
  eval_tf_function: true
  max_to_keep: 5
  optimizer_config:
    ema: null
    learning_rate:
      stepwise:
        boundaries: [1600000, 1800000]
        name: PiecewiseConstantDecay
        values: [0.000325, 3.25e-05, 3.25e-06]
      type: stepwise
    optimizer:
      sgd:
        clipnorm: null
        clipvalue: null
        decay: 0.0
        momentum: 0.949
        name: SGD
        nesterov: false
      type: sgd
    warmup:
      linear:
        name: linear
        warmup_learning_rate: 0
        warmup_steps: 1000
      type: linear
  steps_per_loop: 1000
  summary_interval: 1000
  train_steps: 2002000
  train_tf_function: true
  train_tf_while_loop: true
  validation_interval: 1000
  validation_steps: 1000
